const ListProducts = [
    {
        id: 1,
        image: "./images/product-1.jpg",
        discount: "30%",
        category: "vegetables",
        name: "bell peper",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 2,
        image: "./images/product-2.jpg",
        discount: "30%",
        category: "fruits",
        name: "STRAWBERRY",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 3,
        image: "./images/product-3.jpg",
        discount: "30%",
        category: "vegetables",
        name: "GREEN BEANS",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 4,
        image: "./images/product-4.jpg",
        discount: "30%",
        category: "vegetables",
        name: "PURPLE CABBAGE",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 5,
        image: "./images/product-5.jpg",
        discount: "30%",
        category: "fruits",
        name: "TOMATOE",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 6,
        image: "./images/product-6.jpg",
        discount: "30%",
        category: "vegetables",
        name: "BROCOLLI",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 7,
        image: "./images/product-7.jpg",
        discount: "30%",
        category: "vegetables",
        name: "CARROTS",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 8,
        image: "./images/product-8.jpg",
        discount: "30%",
        category: "juice",
        name: "FRUIT JUICE",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 9,
        image: "./images/product-9.jpg",
        discount: "30%",
        category: "vegetables",
        name: "ONION",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 10,
        image: "./images/product-10.jpg",
        discount: "30%",
        category: "fruits",
        name: "APPLE",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 11,
        image: "./images/product-11.jpg",
        discount: "30%",
        category: "vegetables",
        name: "GARLIC",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    },
    {
        id: 12,
        image: "./images/product-12.jpg",
        discount: "30%",
        category: "vegetables",
        name: "CHILLI",
        price: 120000,
        sale_price: "$80.00",
        expiration_date: "25/12/2021",
        quantity: "10",
        description: "khong description",
    }
]

export default ListProducts;